[package]
name = "shader_test"
version = "0.1.0"
edition = "2021"

[dependencies]
# gl = "0.14.0"
# glutin = "0.32.1"
png = "0.17.14"
rand = "0.8.5"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug-assertions = false
strip = true
panic = "abort"
